site_name: 'Tom Hazledine'
permalink: /:title
markdown: kramdown
include: ['.htaccess']
exclude: [sass/]
kramdown:
  auto_ids: false
paginate: 1
name: Tom Hazledine
description: The personal web-hub for Tom Hazledine
feed_url: http://thomashazledine.com/feed.xml
exclude: [config.rb, gruntfile.js, root.css, sass, favicon_sizes, social_icons, package.json, node_modules]
