site_name: 'Tom Hazledine'
permalink: /:title
markdown: kramdown
exclude: [sass/]
kramdown:
  auto_ids: false
paginate: 1
name: Tom Hazledine
description: The personal web-hub for Tom Hazledine
feed_url: http://thomashazledine.com
exclude: [/img/favicon_sizes/, /img/social_icons/, /sass/, config.rb, README.md]