site_name: 'Tom Hazledine'
version: '4.0'
permalink: /:title
markdown: kramdown
include: ['.htaccess']
exclude: [sass/]
kramdown:
  auto_ids: false
name: Tom Hazledine
description: The personal web-hub for Tom Hazledine
feed_url: http://thomashazledine.com/feed.xml
exclude: [config.rb,
          gruntfile.js,
          root.css,
          sass,
          favicon_sizes,
          social_icons,
          package.json,
          notes*.md,
          img/design_files*,
          img/raw*,
          node_modules]
navigation:
  - text: About
    url: /
  - text: Portfolio
    url: /portfolio/
  - text: Blog
    layout: post
    url: /blog/
